apiVersion: v1
kind: Service
metadata:
  name: load-and-stress-service
spec:
  selector:
    app: load-and-stress
  ports:
  - protocol: "TCP"
    port: 5100
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-and-stress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: load-and-stress
  template:
    metadata:
      labels:
        app: load-and-stress
    spec:
      containers:
      - name: load-and-stress
        image: load-and-stress:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
